apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-greeter
spec:
  template:
    metadata:
      labels:
        app: grpc-greeter
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/hipster-apim-demo/nodegreeter
        ports:
        - containerPort: 50051        
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-greeter
spec:
  type: ClusterIP
  selector:
    app: grpc-greeter
  ports:
  - port: 80
    targetPort: 50051
    protocol: TCP
    name: grpc
  

