apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ws-echo
spec:
  template:
    metadata:
      labels:
        app: ws-echo
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/hipster-apim-demo/websocket-echo
        ports:
        - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: ws-echo
spec:
  type: ClusterIP
  selector:
    app: ws-echo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http